import os

file_path = r'c:\Users\ASUS\Documents\trae_projects\People_Mechine_Project\android\app\src\main\java\com\example\stressassessment\MainActivity.java'
os.makedirs(os.path.dirname(file_path), exist_ok=True)

code = 'package com.example.stressassessment;\n\nimport android.os.Bundle;\nimport android.view.View;\nimport android.view.Window;\nimport android.view.WindowManager;\nimport android.webkit.WebChromeClient;\nimport android.webkit.WebSettings;\nimport android.webkit.WebView;\nimport android.webkit.WebViewClient;\nimport androidx.appcompat.app.AppCompatActivity;\n\npublic class MainActivity extends AppCompatActivity {\n    private WebView webView;\n\n    @Override\n    protected void onCreate(Bundle savedInstanceState) {\n        super.onCreate(savedInstanceState);\n\n        requestWindowFeature(Window.FEATURE_NO_TITLE);\n        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,\n                WindowManager.LayoutParams.FLAG_FULLSCREEN);\n\n        setContentView(R.layout.activity_main);\n\n        webView = findViewById(R.id.webview);\n\n        WebSettings webSettings = webView.getSettings();\n        webSettings.setJavaScriptEnabled(true);\n        webSettings.setDomStorageEnabled(true);\n        webSettings.setAllowFileAccess(true);\n        webSettings.setAllowContentAccess(true);\n        webSettings.setLoadWithOverviewMode(true);\n        webSettings.setUseWideViewPort(true);\n        webSettings.setCacheMode(WebSettings.LOAD_DEFAULT);\n        webSettings.setMediaPlaybackRequiresUserGesture(false);\n        webSettings.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);\n\n        webView.setWebViewClient(new WebViewClient());\n        webView.setWebChromeClient(new WebChromeClient());\n\n        hideSystemUI();\n\n        webView.loadUrl("file:///android_asset/www/index.html");\n    }\n\n    private void hideSystemUI() {\n        View decorView = getWindow().getDecorView();\n        decorView.setSystemUiVisibility(\n                View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY\n                | View.SYSTEM_UI_FLAG_LAYOUT_STABLE\n                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION\n                | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN\n                | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION\n                | View.SYSTEM_UI_FLAG_FULLSCREEN);\n    }\n\n    @Override\n    public void onWindowFocusChanged(boolean hasFocus) {\n        super.onWindowFocusChanged(hasFocus);\n        if (hasFocus) {\n            hideSystemUI();\n        }\n    }\n\n    @Override\n    public void onBackPressed() {\n        if (webView.canGoBack()) {\n            webView.goBack();\n        } else {\n            super.onBackPressed();\n        }\n    }\n}\n'

with open(file_path, 'w', encoding='utf-8', newline='\n') as f:
    f.write(code)

print('MainActivity.java created successfully')
print('File exists:', os.path.exists(file_path))
